# Generated by Django 3.2.5 on 2021-09-19 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20210918_2335'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mail',
        ),
    ]
